apiVersion: apps/v1
kind: Deployment
metadata:
  name: thisweek-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: thisweek-app
  template:
    metadata:
      labels:
        app: thisweek-app
    spec:
      containers:
      - name: thisweek-app
        image: josephvano/thisweek:v0.0.1
        ports:
        - containerPort: 8083
